"""JWT auth — minimal HS256 token issuer/verifier for the API.

We use HS256 with a server-side secret (NEXUS_JWT_SECRET, autogenerated
on first run). Tokens are short-lived (default 7 days). Claims are
deliberately minimal: sub (user_id), scope, exp, iat.

No refresh tokens in v1 — clients re-login when the token expires. This
keeps the surface small; we can add refresh + rotation in Phase 2.5.
"""
from __future__ import annotations

import logging
import os
import secrets
import time
from typing import Any

import jwt

logger = logging.getLogger(__name__)

DEFAULT_EXPIRY_SECONDS = 7 * 24 * 3600  # 7 days
_ALGORITHM = "HS256"


def _load_or_create_secret() -> str:
    """Read NEXUS_JWT_SECRET from env, or generate a stable per-installation one.

    The auto-generated secret is stored in a file inside data/ so tokens
    survive service restarts. NOT for production multi-replica deployments —
    production must set NEXUS_JWT_SECRET explicitly.
    """
    env_secret = os.getenv("NEXUS_JWT_SECRET", "").strip()
    if env_secret:
        return env_secret
    # Fallback: a file under data/
    secret_path = os.getenv("NEXUS_JWT_SECRET_FILE", "data/jwt_secret")
    if os.path.exists(secret_path):
        with open(secret_path) as f:
            existing = f.read().strip()
        if existing:
            return existing
    # First boot — generate and persist
    new_secret = secrets.token_urlsafe(64)
    os.makedirs(os.path.dirname(secret_path) or ".", exist_ok=True)
    with open(secret_path, "w") as f:
        f.write(new_secret)
    try:
        os.chmod(secret_path, 0o600)
    except OSError:
        logger.warning("[jwt] could not chmod jwt_secret file to 0600")
    logger.info("[jwt] generated new secret at %s", secret_path)
    return new_secret


_SECRET: str | None = None  # lazy load so tests can override NEXUS_JWT_SECRET


def _secret() -> str:
    global _SECRET
    if _SECRET is None:
        _SECRET = _load_or_create_secret()
    return _SECRET


def reset_secret_cache() -> None:
    """Test hook: clear the cached secret so a new NEXUS_JWT_SECRET takes effect."""
    global _SECRET
    _SECRET = None


def issue_token(user_id: str, scope: str = "user", *, expires_in: int = DEFAULT_EXPIRY_SECONDS) -> str:
    """Create a signed JWT for `user_id` with the given scope."""
    if not user_id:
        raise ValueError("user_id is required")
    now = int(time.time())
    payload = {
        "sub": user_id,
        "scope": scope,
        "iat": now,
        "exp": now + int(expires_in),
    }
    return jwt.encode(payload, _secret(), algorithm=_ALGORITHM)


def verify_token(token: str) -> dict | None:
    """Verify a JWT and return its claims, or None if invalid/expired.

    Returns a dict with at least: sub (user_id), scope, exp, iat.
    """
    if not token:
        return None
    try:
        claims = jwt.decode(token, _secret(), algorithms=[_ALGORITHM])
    except jwt.ExpiredSignatureError:
        return None
    except jwt.InvalidTokenError as exc:
        logger.debug("[jwt] invalid token: %s", exc)
        return None
    if not claims.get("sub"):
        return None
    return claims


def token_from_bearer(authorization_header: str) -> str | None:
    """Extract a raw token from an `Authorization: Bearer <token>` header."""
    if not authorization_header:
        return None
    if authorization_header.startswith("Bearer "):
        return authorization_header[7:].strip() or None
    return None
